const fs = require('fs');

let projects = fs.readFileSync('src/pages/ProjectTracker.tsx', 'utf8');

const newProjects = `const PROJECTS = [
  {
    id: 1,
    title: "Accra Ring Road Phase 2",
    desc: "Major expansion of the inner ring road to ease traffic congestion in the central business district.",
    location: "Ablekuma South",
    region: "Greater Accra",
    mp: "Alfred Okoe Vanderpuije",
    category: "Roads & Transport",
    status: "Ongoing",
    completion: 65,
    budget: "GHC 45M",
    date: "Dec 2026",
    contractor: "GHA Contractors",
    source: "Government",
  },
  {
    id: 2,
    title: "Kumasi Market Complex",
    desc: "Modernization of the central market with improved drainage, fire safety, and 500 new stalls.",
    location: "South Dayi",
    region: "Volta",
    mp: "Rockson-Nelson Dafeamekpor",
    category: "Community Infrastructure",
    status: "Completed",
    completion: 100,
    budget: "GHC 12M",
    date: "Jan 2025",
    contractor: "AshBuild",
    source: "Public-Private",
  },
  {
    id: 3,
    title: "Tamale Hospital Renovation",
    desc: "Upgrading maternity and emergency wards with modern medical equipment.",
    location: "Tamale South",
    region: "Northern",
    mp: "Haruna Iddrisu",
    category: "Healthcare",
    status: "Ongoing",
    completion: 40,
    budget: "GHC 28M",
    date: "Mar 2026",
    contractor: "MediBuild Gh",
    source: "Donor Funded",
  },
  {
    id: 4,
    title: "Cape Coast STEM School",
    desc: "State-of-the-art science and technology high school for gifted students.",
    location: "Ajumako Enyan Essiam",
    region: "Central",
    mp: "Cassiel Ato Baah Forson",
    category: "Education",
    status: "Completed",
    completion: 100,
    budget: "GHC 8M",
    date: "Aug 2025",
    contractor: "EduStruct",
    source: "Government",
  },
  {
    id: 5,
    title: "Volta River Community Water",
    desc: "Installation of mechanized boreholes and purification systems for 5 riverine communities.",
    location: "North Tongu",
    region: "Volta",
    mp: "Samuel Okudzeto Ablakwa",
    category: "Water & Sanitation",
    status: "Upcoming",
    completion: 0,
    budget: "GHC 6M",
    date: "Sep 2026",
    contractor: "Volta Hydro",
    source: "Constituency Fund",
  },
  {
    id: 6,
    title: "Accra Youth Tech Hub",
    desc: "Tech incubator providing high-speed internet, mentorship, and workspace.",
    location: "Klottey-Korle",
    region: "Greater Accra",
    mp: "Zanetor Agyeman-Rawlings",
    category: "Youth Development",
    status: "Delayed",
    completion: 75,
    budget: "GHC 15M",
    date: "Jul 2025",
    contractor: "TechBuild",
    source: "Public-Private",
  },
];`;
projects = projects.replace(/const PROJECTS = \[[\s\S]*?\];/m, newProjects);
fs.writeFileSync('src/pages/ProjectTracker.tsx', projects);
